### ISSUE TITLE
Disabling firewall

### ISSUE THREAD

**Issue by FlickDESIGN** [tribotissues/tribotissues#10]
Hello. I am new and quite happy user of Tribot and I quickly realized how problematic your firewall is. Recently there were new servers added and I would need to add all of them manually. It's really annoying to let account farm over night just to wake up next day and see it worked one hour and then asked if it can jump to other server. We are asking it since few years:

https://tribot.org/forums/topic/17635-disable-firewall/
https://tribot.org/forums/topic/69330-disable-firewall-auto-allow-requests/
https://tribot.org/forums/topic/45536-allow-us-to-disable-the-tribot-firewalltoo-many-prompts/
https://tribot.org/forums/topic/69544-firewall-prompts/

I know this will be huge security flaw but a lot of people would appreciate that. I trust my developer and I would be very happy to use this option. 99% of us click "Allow all" on each promp anyways. Thanks for reading.

**Comment by towicode** [comment]
Should be included in next release
