### ISSUE TITLE
Projection class failing in Fixed mode

### ISSUE THREAD

**Issue by Netami1** [tribotissues/tribotissues#103]
Description of the bug (be specific): Projection#isInMinimap returns false when the tile is inside the minimap and clickable in fixed mode.

How often the bug occurs: Every time for some users, never for others. Deleting hooks.dat does not appear to help.

Triggers of the bug (if known): Calling Projection#isInMinimap, seems to be related to switching between resizeable and fixed mode.

Java version: JDK 1.8.0_144

Max Heap Size: 512

TRiBot client version: 9.310_0

Looking Glass (yes/no): no

Operating System: Windows 10

Script Name: Netami's Pest Control

TRiBot Old-School or RS3: Old-School

Client Debug: None

Bot Debug: None

Screenshots (if any): None

**Comment by TRiLeZ** [comment]
Is this still an issue? It may be fixed now as a result of fixing a different bug.

**Comment by FALSkills** [comment]
It is still an issue. I am not sure what is causing it, but the client will flicker and then the isInMinimap method will work again.

**Comment by TRiLeZ** [comment]
Is this still an issue after the latest release?

**Comment by Netami1** [comment]
Fixed, thanks.
