### ISSUE TITLE
Objects hook broken

### ISSUE THREAD

**Issue by FALSkills** [tribotissues/tribotissues#107]
Description of the bug (be specific):
Objects.find methods return arrays of length 0.
How often the bug occurs:
Everytime
Triggers of the bug (if known):
5/10/2018 OSRS update
Java version:
8u45
Max Heap Size:
512mb
TRiBot client version:
TRiBot Release 9.311_0 loaded.
Looking Glass (yes/no):
no
Operating System:
Windows 8.1 / 10
Script Name:
n/a
TRiBot Old-School or RS3:
Old-School
Client Debug:
println(Objects.getAll(10).length);
prints 0 (I'm at Castle Wars bank chest)
Bot Debug:

Screenshots (if any):

**Comment by TRiLeZ** [comment]
Was fixed yesterday.
