### ISSUE TITLE
Object RSMenuNodes not detected properly, Banking.openBank affected?

### ISSUE THREAD

**Issue by Aropupu** [tribotissues/tribotissues#108]
Description of the bug (be specific): Any clicking method using RSMenuNode detection will fail to click on the object. Banking.openBankBooth and openBank seem to also be having trouble clicking on objects so I assume they also use this method.

How often the bug occurs: Any time Clicking.click(FilterRSMenuNode filter, Clickable07... entity) is used, at least when both containsAction and correlatesTo are used in the filter.

Triggers of the bug (if known):

Java version: jdk1.8.0_171

Max Heap Size: 386

TRiBot client version: 9.311_1

Looking Glass (yes/no): no

Operating System: Windows 10

Script Name: any

TRiBot Old-School or RS3: osrs

Client Debug:

Bot Debug:

Screenshots (if any):

**Comment by TRiLeZ** [comment]
Fixed in the next release.
