### ISSUE TITLE
General.isClientResizable() is not consistent

### ISSUE THREAD

**Issue by easyaspieee** [tribotissues/tribotissues#110]
Description of the bug (be specific):
The method returns true even if the game mode is set to fixed
How often the bug occurs:

It seems to be related to the window size allowed when starting the client. If it is smaller than it should be (the entire game window does not fit), then client sees it as resizeable mode. If I resize back to a bigger screen which leaves black sides (so you know the entire client fits), the method starts acting as expected.

If you resize it BACK from good to bad though, it still works as expected.

Triggers of the bug (if known):
Calling the method
Java version:
1.8.0_161
Max Heap Size:
386MB
TRiBot client version:
9.311_2
Looking Glass (yes/no):
No
Operating System:
Windows 10
Script Name:
N/A
TRiBot Old-School or RS3:
OSRS
Client Debug:
N/A
Bot Debug:
N/A
Screenshots (if any):

**Comment by TRiLeZ** [comment]
Is this issue fixed for you in the latest release?
