### ISSUE TITLE
Client Starter NPE

### ISSUE THREAD

**Issue by FALSkills** [tribotissues/tribotissues#19]
Description of the bug (be specific):
A client will occasionally get a null pointer in the bot debug and fail to start the script.
How often the bug occurs:
Infrequently.
Triggers of the bug (if known):
It seems to happen more often when loading many clients at once.
Java version:
java 8u60
Max Heap Size:
512mb
TRiBot client version:
9.305_0 but it has been present for a very long time.
Looking Glass (yes/no):
no
Operating System:
Windows Server 2008 R2
Script Name:
n/a
TRiBot Old-School or RS3:
OS
Client Debug:
none
Bot Debug:
[04:16:34] Exception in thread "Thread-13" 
[04:16:34] java.lang.NullPointerException
[04:16:34] 	at obf.Ol.run(vo:703)
[04:16:34] 	at java.lang.Thread.run(Thread.java:745)
Screenshots (if any):
n/a

**Comment by FALSkills** [comment]
Error on current update:
Exception in thread "Thread-13"
java.lang.NullPointerException
at obf.sl.run(eu:439)
at java.lang.Thread.run(Unknown Source)

**Comment by TRiLeZ** [comment]
Not sure if this is still an issue, so I'm closing it.
