### ISSUE TITLE
WebWalking stuck on fences

### ISSUE THREAD

**Issue by Netami1** [tribotissues/tribotissues#2]
Description of the bug (be specific): Webwalking will often get stuck going around objects/areas that it can/cannot reach. Example in video: https://vid.me/1iWx

How often the bug occurs: about 50% of the time, on a per account basis

Triggers of the bug (if known): WebWalking anywhere, in this case going from Lumbridge to Varrock.

Java version: 1.80_101 64 bit

Max Heap Size: 1024 MB

TRiBot client version: Release 9.303_6

Looking Glass (yes/no): No

Operating System: Ubuntu

Script Name: Private

TRiBot Old-School or RS3: Old-school

Client Debug: None

Bot Debug: None

Screenshots (if any): https://vid.me/1iWx

**Comment by towicode** [comment]
Probably gonna be slow/non committal on this. revamping the entire web walker is a priority atm.

**Comment by daxmagex** [comment]
There won't be a rewrite on the current tribot webwalker anytime soon. Anyone experiencing this problem can use [https://github.com/daxmagex/Runescape-Web-Walker-Engine](url) which supports much more areas.
