### ISSUE TITLE
LoginBot chooses PvP worlds

### ISSUE THREAD

**Issue by FALSkills** [tribotissues/tribotissues#21]
Description of the bug (be specific):
Upon trying to log into a free world when they are in a member location, the login bot automatically chooses a new world and attempts the login from there. It is occasionally picking worlds 25 and 37, which are PvP worlds. Those worlds should be excluded from the list of options, as well as 45 (but I haven't seen it log in to that one), and 29 since it's frequently full.
How often the bug occurs:
Randomly.
Triggers of the bug (if known):
Recent login bot changes I would imagine.
Java version:
8u60
Max Heap Size:
512
TRiBot client version:
9.305_0
Looking Glass (yes/no):
no
Operating System:
Windows 
Script Name:
n/a
TRiBot Old-School or RS3:
Old-School
Client Debug:
n/a
Bot Debug:
n/a
Screenshots (if any):

**Comment by TRiLeZ** [comment]
Fixed in 9.305_8.

**Comment by FALSkills** [comment]
@TRiLeZ https://gyazo.com/017c891232e7eda3b61a442a718dce68
Could you please blacklist from your login bot? This happens frequently based upon time of day, and with RS mobile coming in late 2017 it may be even more frequent.
