### ISSUE TITLE
Clicking.click inconsistent return times

### ISSUE THREAD

**Issue by Netami1** [tribotissues/tribotissues#25]
Description of the bug (be specific): Calling Clicking.click(Clickable object) causes inconsistent return times, up to several seconds while run in a loop.

How often the bug occurs: Roughly 1-2 times in a 3 second loop

Triggers of the bug (if known): Calling Clicking.click

Java version: 1.8.0_121

Max Heap Size: 1024MB

TRiBot client version: 9.305_5

Looking Glass (yes/no): No

Operating System: Ubuntu 16.04

Script Name: Private

TRiBot Old-School or RS3: Old-School

Client Debug: None

Bot Debug: None

Screenshots (if any): 
http://i.imgur.com/uXTxHXD.png - WIth a sleep of General.randomSD(50,25) in between each click. Notice the 2+ second pause in between inside the loop.

Code Used: `while (true) {
                    General.println("Time since last click - " + (System.currentTimeMillis() - lastClick));
                    lastClick = System.currentTimeMillis();
                    if(Clicking.click("Fight",toFight)){
                        General.sleep(General.randomSD(50,25));
                    }
                }`

**Comment by Netami1** [comment]
Same issue as #28

**Comment by erickho123** [comment]
Fixed in tribot latest update?
https://tribot.org/forums/topic/72574-tribot-release-9305_6/#comment-846453
