### ISSUE TITLE
World List Updated

### ISSUE THREAD

**Issue by FALSkills** [tribotissues/tribotissues#30]
Description of the bug (be specific):
They added new worlds today, which changed the layout of the world select screen and added new worlds that are not automatically allowed by the firewall.
New IPs are these I'm pretty sure - the last one might not be right though:
113.29.20.117
113.29.20.118
113.29.20.119
113.29.20.120
113.29.20.121
113.29.20.122

Due to the world select layout changing, the login bot cannot accurately pick a new world upon receiving login responses that would lead it to world hop. This leads to a near endless loop of it trying to pick a world, failing to choose the proper world, and then trying to pick a new world.
I am not sure how the code is on the client for choosing the boxes to click, but here is my updated method to grab the rectangles, with the old version commented out. 
```
private static Rectangle getRectangle(int index){
//		int x = ((int) ((Math.floor(index) / 17) % 5) * 93) + 157;
//		int y = ((int) (Math.ceil(index) % 17) * 24) + 60;
		int x = ((int) ((Math.floor(index) / 18) % 5) * 93) + 157;
		int y = ((int) (Math.ceil(index) % 18) * 24) + 49;
		return new Rectangle(x,y,81,18);
}
```

How often the bug occurs:
n/a
Triggers of the bug (if known):
Today's update
Java version:
any
Max Heap Size:
any
TRiBot client version:
n/a
Looking Glass (yes/no):
n/a
Operating System:
n/a
Script Name:
n/a
TRiBot Old-School or RS3:
Old-School
Client Debug:
n/a
Bot Debug:
n/a
Screenshots (if any):

**Comment by TRiLeZ** [comment]
Fixed in 9.305_8.
