### ISSUE TITLE
MessageListening07 not working

### ISSUE THREAD

**Issue by FALSkills** [tribotissues/tribotissues#31]
Description of the bug (be specific):
MessageListening07 does not receive game messages, instead they are printed to the Bot Debug followed by a (-1)
How often the bug occurs:
Everytime
Triggers of the bug (if known):
7/13/2017 RS update
Java version:
8u111
Max Heap Size:
512
TRiBot client version:
TRiBot Release 9.305_6
Looking Glass (yes/no):
no
Operating System:
Windows
Script Name:
n/a
TRiBot Old-School or RS3:
OS
Client Debug:
n/a
Bot Debug:
[10:27:28] : You dig a hole in the ground...(-1)
[10:27:29] : You bury the bones.(-1)
Screenshots (if any):

**Comment by TRiLeZ** [comment]
Fixed with 9.305_7.
