### ISSUE TITLE
Clicking entities broken + more

### ISSUE THREAD

**Issue by FALSkills** [tribotissues/tribotissues#35]
Description of the bug (be specific):
Calling Clickable#click() results in an empty right click on the entity and returns false. (not sure if its exclusive to Clickable07 or Clickable, but obviously its for Old-School)
The Mouse.click() functions still works.

Additional problems:
Uptext hook is broken.
ChooseOption menu node hook is broken (probably related to above), but returns array length -1 for getOptions and array length 0 for getMenuNodes, but ChooseOption.isOpen works.
Debug Object names shows null, but the RSObjectDefinition is working.

How often the bug occurs:
Every time
Triggers of the bug (if known):
Today's RS update
Java version:
8u111
Max Heap Size:
512
TRiBot client version:
9.305_8
Looking Glass (yes/no):
no
Operating System:
Windows 8.1
Script Name:
n/a
TRiBot Old-School or RS3:
old-school
Client Debug:
n/a
Bot Debug:
n/a
Screenshots (if any):
n/a

**Comment by Marketingguru** [comment]
I am experiencing issues logging out. This must be why.

**Comment by TRiLeZ** [comment]
Solved in 9.305_9.
