### ISSUE TITLE
GameTab.open(TABS.INVENTORY)

### ISSUE THREAD

**Issue by fmorris2** [tribotissues/tribotissues#36]
Doesn't work when Kourend Favor tab is open in the quest tab:
https://gyazo.com/90ed938430dabb0fb6b8b52996b80196

If that tab is currently selected, GameTab.open(TABS.INVENTORY) does nothing and returns **true**

**Comment by TRiLeZ** [comment]
Will be fixed in the next release. I'm assuming the tab's formal name is "Kourend Favour". The proper name is needed for the fix to work.
