### ISSUE TITLE
WorldHopper#changeWorld Clicks between worlds

### ISSUE THREAD

**Issue by iFluffee** [tribotissues/tribotissues#39]
Description of the bug (be specific): The World Hopper clicks between worlds instead of selecting the proper world.

How often the bug occurs: Most of the time, it may occasionally get lucky and click a world. However, if it doesn't click the proper world it just loops until it gets lucky and clicks the proper world.

Triggers of the bug (if known): Calling the changeWorld function, or if the LoginBot needs to change worlds by itself.

Java version: JDK 1.8.0_131

Max Heap Size: 256 mb

TRiBot client version: 9.305_10

Looking Glass (yes/no): No

Operating System: Debian 8 (Jessie)

Script Name: https://i.imgur.com/nh0Ar5u.png 

TRiBot Old-School or RS3: Old-School

Client Debug: N/A

Bot Debug: N/A

Screenshots (if any): https://i.imgur.com/m0uB7x6.gif - Stolen from Dax's post.

**Comment by JoeDezzy1** [comment]
I have experienced this as well

**Comment by TRiLeZ** [comment]
Fixed in 9.305_11.
