### ISSUE TITLE
Magic.selectSpell bug

### ISSUE THREAD

**Issue by FALSkills** [tribotissues/tribotissues#4]
Description of the bug (be specific): Magic.selectSpell can only select spells that have the action "Cast". The Arceuus reanimation spells have the action "Reanimate". It will keep right clicking the spell in attempt to click the option "Cast".  A work-around is to interact with the interface yourself.

How often the bug occurs: Every time

Triggers of the bug (if known): New spellbook with Zeah (Although at this point it's old)

Java version: n/a (8u112)

Max Heap Size: 512

TRiBot client version: 9.304_3

Looking Glass (yes/no): n/a

Operating System: n/a

Script Name: n/a

TRiBot Old-School or RS3: Old-School

Client Debug: n/a

Bot Debug: n/a

Screenshots (if any):

https://gyazo.com/73c170fb68f1380ffd8d8d4dd4e6a9b4

https://gyazo.com/5274792318e1a8b74ac53515c13ecd86

 

It is also noteworthy that Magic.selectSpell does not take into account whether or not the interface is hidden, which occurs when the player is on a different spellbook.

**Comment by tribotissues** [comment]
is the only other option Reanimate? If so it should be pretty simple to add.

**Comment by FALSkills** [comment]
Yes. I just checked out the other spellbooks, and every other spell has the action "Cast". So the only new action would be "Reanimate"

**Comment by towicode** [comment]
Fixed will be released soon
