### ISSUE TITLE
WorldHopper.getRandomWorld(true)

### ISSUE THREAD

**Issue by JoeDezzy1** [tribotissues/tribotissues#41]
Description of the bug (be specific):
Returns non-existent worlds sometimes

How often the bug occurs:
Moderately frequent.

Triggers of the bug (if known):
Calling WorldHopper.getRandomWorld(true) and WorldHopper.getRandomWorld(true, false);

Java version:
java 1.8.0_101

Max Heap Size:
256mb

TRiBot client version:
Lastest

Looking Glass (yes/no):
no

Operating System:
OSX

Script Name:
n/a

TRiBot Old-School or RS3:
OS

Client Debug:
none

Bot Debug:
Screenshots (if any):

![screen shot 2017-08-01 at 4 18 54 pm](https://user-images.githubusercontent.com/6827851/28845258-66ebfeec-76d5-11e7-93bd-c26e3b5a7041.png)
![screen shot 2017-08-01 at 4 19 25 pm](https://user-images.githubusercontent.com/6827851/28845264-6a7d714e-76d5-11e7-9f73-3bb2fa36268a.png)
![screen shot 2017-08-01 at 4 19 31 pm](https://user-images.githubusercontent.com/6827851/28845271-70bf6562-76d5-11e7-9cb3-7188eccbf498.png)

**Comment by TRiLeZ** [comment]
Fixed in 9.305_11.
