### ISSUE TITLE
Game client crashing to black screen when world hopping

### ISSUE THREAD

**Issue by godspower33** [tribotissues/tribotissues#43]
Description of the bug (be specific):
**Using the default api world hopper or any world hopper, the client will crash randomly to a black canvas where the game normally is. Sometimes it will recover and continue however majority of the time it will stay black. This happens when hopping worlds often.** 

**The bug happens when it clicks the button on the login screen "Click here to switch" the game canvas will freeze however you can still use other tribot functions, only the canvas freezes**

How often the bug occurs:

**This bug happens very often.**

Triggers of the bug (if known): 

**World hopping multiple times.**

Java version:

**1.8.0_111 64bit**

Max Heap Size:

**386MB**

TRiBot client version:
**9.305_11**
Looking Glass (yes/no):
**No**
Operating System:
**Windows 10, Windows 2012, Windows 2008, Debian 8, all OS**

Script Name:

**This bug can happen on any script, I wrote a test script that only world hops to test if it was a script specific bug or not and it is not. The only thing in the test script was world hopping, waiting 5 seconds then world hopping again.**

TRiBot Old-School or RS3:

_**Old-School**_

Client Debug:

**No client debug available when the client crashes to black.**

Bot Debug:

**No client debug available when the client crashes to black.**

Screenshots (if any):

**Comment by towicode** [comment]
I'm trying to reproduce with this

```
	public void run() {

		//super.setLoginBotState(true);
		
		
		while (true) {
			WorldHopper.changeWorld(7);
			sleep(10000);
			WorldHopper.changeWorld(26);
		}

	}
```

but I can't seem to reproduce this bug
