### ISSUE TITLE
All scripts failing to select correct options in inventory

### ISSUE THREAD

**Issue by Jacobcapra** [tribotissues/tribotissues#54]
For all scripts I am trying to run (mining & fletching mainly) the script cannot correctly select the right-click options for the items in my inventory.

For example, with logs and a knife in my inventory, the second log from the left in the top row is right-clicked and then the cursor moves to the left two spaces (outside of my inventory interface).

How often this bug occurs: Always

Java Version 8.151

OS: Windows 10

OSRS

Screenshot: https://imgur.com/3ozwScL

**Comment by FALSkills** [comment]
Resizeable mode is not supported. Please use fixed.
