### ISSUE TITLE
GrandExchange#offer fails to use amount prompt

### ISSUE THREAD

**Issue by WBScripts** [tribotissues/tribotissues#55]
This method gets stuck when entering in the amount to buy or price. It seems to fail to recognize the prompt for input.

There are likely other various related issues.

How often the bug occurs: Every time
Heap Size: 300MB
Java Version: 1.8.0_112 64bit
Operating System: Windows 10
TRiBot Version: TRiBot Release 9.305_14

**Comment by towicode** [comment]
Should be fixed in next release
