### ISSUE TITLE
Scripts stop working after a RS Update

### ISSUE THREAD

**Issue by erickho123** [tribotissues/tribotissues#56]
Description of the bug (be specific):
Whenever runescape updates, scripts stop working until you restart TRiBot twice after loading runescape.
Most users will only restart the client once (as intended), and think the script is broken.
This bug causes item definitions, npc definitions, item definitions, and many other apis to break.
It has something to do with hooks.dat, maybe.

How often the bug occurs:
Always when rs updates

Triggers of the bug (if known):
RS UPDATE

Java Home:: jdk 151

Max Heap Size:
386

TRiBot client version:
9.305_14

Looking Glass (yes/no):
No

Operating System:
Windows 10

Script Name:
N/A

TRiBot Old-School or RS3:
Old-School

Client Debug:
Nothing

Bot Debug:
https://pastebin.com/raw/pEpkkXML

Screenshots (if any):

**Comment by TRiLeZ** [comment]
Was fixed a while ago.
