### ISSUE TITLE
Unable to detect 64 bit JDK on non C drives (Windows)

### ISSUE THREAD

**Issue by iFluffee** [tribotissues/tribotissues#57]
Description of the bug (be specific): The TRiBot Loader is unable to detect the 64 bit JDK when it is installed on a non C drive. In this case, the 64 bit JDK was installed on the user's F drive rendering TRiBot unable to detect the install. However, TRiBot had no issue detecting a 32 bit JDK, or a 64 bit JRE when installed on the same drive. Only 64 bit JDK had the issue

How often the bug occurs: Presumably whenever a 64 bit JDK is installed on a non C drive

Triggers of the bug (if known): Installing 64 bit JDK on a non C drive

Java version: JDK 151 (x64) and JDK 141 (x64) were tested.

Max Heap Size: 512

TRiBot client version: 9.305_14

Looking Glass (yes/no): Yes

Operating System: Windows 10

Script Name: N/A

TRiBot Old-School or RS3: Old-School

Client Debug: N/A

Bot Debug: N/A

Screenshots (if any): N/A

**Comment by towicode** [comment]
Does this happen for you Fluf?

**Comment by tribotissues** [comment]
I was unable to reproduce this bug
