### ISSUE TITLE
Resizable mode is not detected

### ISSUE THREAD

**Issue by Laniax** [tribotissues/tribotissues#58]
Description of the bug (be specific): 
TRiBot recognizes if the game canvas is bigger then the size of fixed mode, and will spam the Bot Debug with this message: 'Re-sizable mode is currently not supported. Please change the screen mode to fixed via the regular client.'

However, you can turn on resizeable mode and still be on the window size of fixed mode, in this case, the detection is not triggered.

As a workaround, i've added the code below to my scripts that checks for an interface only present in resizable mode.

 /**

     * Checks if the game is set to resizable mode.  

     * @return true if resizable mode, false if fixed mode.  

     */  

    public boolean isResizableMode() {  

        return Interfaces.get(161, 0) != null;  

    }  

How often the bug occurs: Always

Triggers of the bug (if known): Turn on resizable mode on smallest window size.

Java version: JDK 151 (x64) and JDK 141 (x64) were tested.

Max Heap Size: 368

TRiBot client version: 9.305_14

Looking Glass (yes/no): Both

Operating System: Windows 10

Script Name: N/A

TRiBot Old-School or RS3: Old-School

Client Debug: N/A

Bot Debug: N/A

Screenshots (if any): N/A

**Comment by towicode** [comment]
Thanks!

**Comment by towicode** [comment]
Should be fixed in next release
