### ISSUE TITLE
Linux-Debian: Minimize to System Tray, Unable To Restore Client

### ISSUE THREAD

**Issue by JoeDezzy1** [tribotissues/tribotissues#61]
Description of the bug (be specific):
Minimize to tray function - Client is unable to be restored once it is minimized.
You can see the icon in the task bar, but clicking it or right clicking it provide no available options nor signs of any an interaction. Have tried to use multiple task bars, all the same. Other programs work, it is only with tribot.

How often the bug occurs:
Everytime a call to Settings -> Minimize to System Tray is made

Triggers of the bug (if known):
call Settings -> Minimize to System Tray is made

Java version:
oraclejdk8 

Max Heap Size:
386

TRiBot client version:
Latest

Looking Glass (yes/no):

Operating System:
Debian - Gnome & Xfce

Script Name:
TRiBot Old-School or RS3:
Client Debug:
Bot Debug:
Screenshots (if any):

N/A

**Comment by towicode** [comment]
This likely won't be fixed. However... I would like to setup standards for support one distro of linux and one desktop environment. Likely Ubuntu and Gnome.

**Comment by JoeDezzy1** [comment]
Definitely do it for gnome, and hopefully debian :P

**Comment by tribotissues** [comment]
debian is an operating system, gnome is a desktop environment. If you run gnome on debian it should work fine.

**Comment by JoeDezzy1** [comment]
I know this. I was saying that he should do it for the Gnome Environment. and hopefully for the Debian OS.

**Comment by JoeDezzy1** [comment]
And I have tried it on both gnome and XFCE, neither of them worked. I have even tried it with multiple different types of taskbars

**Comment by TRiLeZ** [comment]
This feature is an old one, specifically intended for use on Windows. Linux doesn't have a "system tray" as far as I'm aware - only a taskbar. It's actually going to be removed in an upcoming release as it is buggy and isn't used by many people.
