### ISSUE TITLE
RSPlayer hook broken

### ISSUE THREAD

**Issue by FALSkills** [tribotissues/tribotissues#63]
Description of the bug (be specific):
Client can no longer grab RSPlayer info including your own RSPlayer's position or any other RSPlayer.
How often the bug occurs:
Everytime
Triggers of the bug (if known):
2/1/2018 RS update
Java version:
1.8.0_45
Max Heap Size:
n/a
TRiBot client version:
TRiBot Release 9.306_0
Looking Glass (yes/no):
no
Operating System:
n/a
Script Name:
n/a
TRiBot Old-School or RS3:
Old-School
Client Debug:
Players.getAll() returns length 0, Player.getPosition (-1,-1,0)
Bot Debug:
n/a
Screenshots (if any):
n/a

**Comment by towicode** [comment]
Fixed
