### ISSUE TITLE
Grand Exchange #offer (buy) fails to type in the item name

### ISSUE THREAD

**Issue by WBScripts** [tribotissues/tribotissues#64]
Description of the bug (be specific): GrandExchange.Offer - buy - fails to type in the item. The interface number was changed slightly with the last update.

The interface for custom price/item/quantity are all changed. Here's a topic discussing it:
https://tribot.org/forums/topic/75941-script-dispute-tau-grand-exchange/

How often the bug occurs: Every time.

Triggers of the bug (if known): All GE custom typing prompts.

Java version: 8

Max Heap Size: 386

TRiBot client version: 9.306_3

Operating System: Win10

**Comment by towicode** [comment]
Will be fixed in next release
