### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by cwilson0005** [tribotissues/tribotissues#69]
Hi there I'm having a problem when I'm using a script with Tribot where I will see a line in the debug section of the program that says "java.lang.OutOfMemoryError: Java heap space" and the script will end. 

It occurs every time I try to use a script.

Launching a script triggers the bug.

Java version: jre1.8.0_161.

Max Heap Size: Have tried from 256MB to 1024MB but the error still occurs.

TRiBot client version: 9.306_4

Looking Glass (yes/no): tried both, still the error occurs

Operating System: Windows 10 64 bit

Script Name: USA Agility

TRiBot Old-School or RS3: Old School

Client Debug: See screenshots

Bot Debug: See screenshots

Screenshots (if any):
![outofheapspace](https://user-images.githubusercontent.com/36211708/35888790-ef9ea91a-0b90-11e8-9876-d4026e916551.jpg)
![outofheapspace 2](https://user-images.githubusercontent.com/36211708/35888792-f130388e-0b90-11e8-887d-3d6315480289.jpg)
![monitor java virtual](https://user-images.githubusercontent.com/36211708/35888796-f2a94f66-0b90-11e8-8bff-d465024d5ecf.jpg)
![1024 heap error](https://user-images.githubusercontent.com/36211708/35888809-fa88e994-0b90-11e8-81da-db000534e3d5.jpg)

![nosoundmenu](https://user-images.githubusercontent.com/36211708/35888797-f3d9ff7a-0b90-11e8-96a5-96be31e141a0.jpg)
![nosound](https://user-images.githubusercontent.com/36211708/35888801-f556f3d0-0b90-11e8-8b43-7774795533f3.jpg)
![heapdumpnosound](https://user-images.githubusercontent.com/36211708/35888803-f70b5dec-0b90-11e8-8379-fa9e8e39b827.jpg)
![1024](https://user-images.githubusercontent.com/36211708/35888808-f8e87d2a-0b90-11e8-9ae5-ee32c3f6b96c.jpg)

**Comment by tribotissues** [comment]
Does this happen with any other script?

**Comment by cwilson0005** [comment]
Yes it happens with woodcutter too: 
![woodcutting heap](https://user-images.githubusercontent.com/36211708/35989987-8e747564-0cfa-11e8-807f-7c3e306c146f.jpg)

**Comment by towicode** [comment]
Try 512 instead of 1024

**Comment by cwilson0005** [comment]
Okay, I tried 512 and the error still occurred: 
![fishing](https://user-images.githubusercontent.com/36211708/36051116-f153f664-0de0-11e8-9d14-d39fd8e96930.jpg)

**Comment by TRiLeZ** [comment]
Seems to me that the scripts are the cause for the heap becoming too full (inefficient scripts). Increasing your heap size can remedy this problem.
