### ISSUE TITLE
Player#getRSPlayer and other player methods

### ISSUE THREAD

**Issue by rsbotmoo** [tribotissues/tribotissues#70]
Description of the bug (be specific):
Multiple Player methods(Players.find(name)) & Player.getRSPlayer().getName() keeps returning NULL until I restart tribot client. It has always worked until last update where the RSPLayer hook was broken.
No point in catching the null value since it keep returning it & I need it playername to push to database.

How often the bug occurs: always after few hours

Triggers of the bug (if known): idk

Java version:

Max Heap Size:

TRiBot client version:

Looking Glass (yes/no): YES

Operating System: CENTOS but also windows I think

Script Name: Private script

TRiBot Old-School or RS3:

Client Debug: Nullpointer

Bot Debug: /

Screenshots (if any):

**Comment by tribotissues** [comment]
Interesting. I'll look into the source code to see why this is happening. Are you reattempting when you get a NULL response? You should always have NULL check and limited reattempts programed into your scripts.

**Comment by rsbotmoo** [comment]
The script loads the display name & checks values in database, it always works on first start of the script, when I have to rerun script sometimes it gives nullpointers. This happens on this line: 
String name = Player.getRSPlayer().getName().replace("\u00a0", " ");
Null checking won't fix the problem since I need to get values from database in order to make the script running. before the update from 1/02/18 it always worked 100%. If I rerun the script it keeps getting NULL values.
Also reattempting getting the value also won't fix this since it keeps returning NULL untill I restart tribot client.

Also, I'm getting null values from RSplayer#find and filters on players.

I was using this method before update

    RSPlayer[] players = Players.find(new Filter<RSPlayer>() {     @Override     public boolean accept(RSPlayer rsPlayer) {         return rsPlayer!=null &&                 rsPlayer.getName()!=null &&                 rsPlayer.getPosition().getY() > tile[0].getPosition().getY()                 && !rsPlayer.getName().equals(Scriptname.playerName);     } });

but somehow it accepts rsPlayer NULL values now (I added rsPlayers!=null after update)

I think it's an issue with Player object returning NULL values, before the update there wasn't really an issue with this, Player.getrsplayer() never returned NULL(unless logged out maybe).

I can show it live on a server of mine if you'd like.

**Comment by towicode** [comment]
Okay I will attempt to reproduce this.

**Comment by TRiLeZ** [comment]
Was fixed a while ago.
