### ISSUE TITLE
Client size gets chopped if the bottom slider is moved

### ISSUE THREAD

**Issue by easyaspieee** [tribotissues/tribotissues#87]
I know you didn't understand the title so here it goes

Description of the bug (be specific):
If you move the slider of bot/client debug up so it covers some of the game screen, then move it down, the screen won't resize and the area that was covered by the debugs is unclickable for both human and bot. It goes back to normal after SOME time (or some other trigger, I had it minimized and when I pulled it back up it was ok again, until I moved the slider again)

How often the bug occurs:

Every time you resize the debug

Triggers of the bug (if known):

Resizing the debug so it covers the game screen

Java version:

1.8.0_161

Max Heap Size:

512MB
TRiBot client version:
9.309_1

Looking Glass (yes/no):
no
Operating System:
Both linux and windows
Script Name:
N/A
TRiBot Old-School or RS3:
OSRS
Client Debug:
Not needed
Bot Debug:
Not needed
Screenshots (if any):
https://imgur.com/a/ryopQ8V

**Comment by TRiLeZ** [comment]
I believe this issue has been fixed now.
