### ISSUE TITLE
Interface 162 loads in the wrong position after Restarter.restartClient is called

### ISSUE THREAD

**Issue by qazteck** [tribotissues/tribotissues#9]
Description of the bug (be specific): Interface 162 (the chat box) loads at the top of the screen
How often the bug occurs: every time
Triggers of the bug (if known): Restarter.restartClient
Java version: 1.8.0_112 64bit
Max Heap Size: 256MB
TRiBot client version: 9.304_5
Looking Glass (yes/no): no
Operating System: Windows 10
Script Name:
TRiBot Old-School or RS3: Old-School
Client Debug:
Bot Debug:
Screenshots (if any):
![](http://i.imgur.com/eSvmVj7.png)

**Comment by towicode** [comment]
This will need to be investigated

**Comment by erickho123** [comment]
Restarter#restartClient was pretty much made for RS3 (though it kinda works with 07)

What's your purpose in using it?

**Comment by qazteck** [comment]
I was using it to restart the client if the login fails like for 6 hour limit, when not using the default login bot.

**Comment by erickho123** [comment]
@qazteck In RS 07, you're not required to restart your client whenever it logs you off after 6 hours.

**Comment by qazteck** [comment]
Oh, lol
