### ISSUE TITLE
Client Paint Delay (Doesn't save settings)

### ISSUE THREAD

**Issue by Duhstin** [tribotissues/tribotissues#90]
Description of the bug (be specific): Client Paint Delay in settings doesn't save after closing client. I've always used paint delay because my scripts doesn't require higher FPS.

How often the bug occurs: Every time

Triggers of the bug (if known): N/A

Java version: 1.8.0_121-b13

Max Heap Size: 384

TRiBot client version: 9.309.1

Looking Glass (yes/no): no

Operating System: Windows 10 Pro

Script Name: N/A

TRiBot Old-School or RS3: Oldschool

Client Debug: N/A

Bot Debug: N/A

Screenshots (if any): N/A

**Comment by FALSkills** [comment]
It is working for me on same OS. Make sure you don't have another client open with a different paint delay value.

**Comment by towicode** [comment]
Gonna close this with FALSkills comment, If you want to repoen it with more info feel free.

**Comment by Duhstin** [comment]
Closed all clients, still doesn't save it when reopening.

**Comment by Duhstin** [comment]
https://www.youtube.com/watch?v=dZoSirXOWDo Proof it's not saving.

**Comment by FALSkills** [comment]
Are you doing anything like syncing your .settings folder across machines?

**Comment by Duhstin** [comment]
Nope.

**Comment by FALSkills** [comment]
If it's not working across all of those, then I would re-open the issue with as much info as you can. That video doesn't look like Windows 10 Pro.

**Comment by Duhstin** [comment]
I've noticed it does save the delay setting in general.ini, however soon as I open another client, and login. It reverts it back to 0 every time.
