### ISSUE TITLE
Interfaces not updating properly

### ISSUE THREAD

**Issue by FALSkills** [tribotissues/tribotissues#96]
Description of the bug (be specific):
Trading.getWindowState() is occasionally returning non-null values when it is not up, and poll interface (master 345) was also listed as up in the interface explorer when it was closed.
How often the bug occurs:
Random and infrequently.
Triggers of the bug (if known):
Tribot resizable update TRiBot Release 9.309_1 loaded.
Java version:
8u45, 8u111
Max Heap Size:
512mb
TRiBot client version:
TRiBot Release 9.309_1 loaded.
Looking Glass (yes/no):
no
Operating System:
Windows 10, Windows 8, Windows server 2008
Script Name:
n/a
TRiBot Old-School or RS3:
old-school
Client Debug:
n/a
Bot Debug:
n/a
Screenshots (if any):
Here is an example of the poll interface (which is closed) being listed as open, which would coincide with the Trading.getWindowState() returning a non-null value even though it wasn't open.
https://gyazo.com/13aa99c41a6c55c7a1a839bfb71aa2a8

**Comment by FALSkills** [comment]
Trading.getWindowState() and Trading.hasAccepted() are still returning inconsistent values after TRiBot Release 9.310_0. 
Trading.getWindowState() will sometimes return null even though it is up.
Trading.hasAccepted() will sometimes return false even though it is true.

**Comment by FALSkills** [comment]
I have been advised by Todd to use a 100ms duration waitCondition when checking if an RSInterface is currently up. This unfortunately will slow down some aspects of scripts, but for now is how we are to deal with Interfaces since the way they are updated has been changed.

**Comment by TRiLeZ** [comment]
The new solution is to call RSInterface#isInterfaceSubstantiated.
